code/b-parasite/config/prst_config.h

As I noticed (only now...) during testing of #6 , the pinout for the E73 modules is slightly different in regard to GPIO pins. I have added a `#ifdef` to the config section where it is relevant (only the fast discharge enable pin). Turns out with it working this thing is more precise than without! :D

Fix pinout for fast discharge pin on E73...E

---

code/b-parasite/src/prst/adc.c

The ADC seems to return values lower than 0 in very dark situations, possibly due to noise.
If this happens, the resulting lux value is 65535, obviously inaccurate. This PR does fix that.

Fix ADC Overflow with dark environment

---

code/b-parasite/config/prst_config.h
code/b-parasite/src/prst/ble.c

Each nRF52 chip comes preprogrammed with a random static MAC address.
This is the default MAC address that is used if we don't specify one.
Fixes #25

Add support for using the nRF52 preprogrammed random MAC address

---

bridge/parahub.yaml
code/b-parasite/README.md
code/b-parasite/config/prst_config.h
code/b-parasite/src/main.c
code/b-parasite/src/prst/ble.c
code/b-parasite/src/prst/ble.h
code/b-parasite/src/prst/shtc3.c
code/b-parasite/src/prst/shtc3.h

The only change from v1 is how the temperature is encoded. In v2, two
bytes at offset 4 and 5  represent a 16-bit signed int (in big-endian).
It contains the temperature in degrees Celsius *  100.
Fixes #29

Implements BLE protocol v2

---

code/b-parasite/config/prst_config.h
code/b-parasite/src/main.c
code/b-parasite/src/prst/ble.c
code/b-parasite/src/prst/ble.h
code/b-parasite/src/prst/data.h

This protococol (https://bthome.io/) allows for automatic sensor
detection in Home Assistant, as long as the device broadcasts its
sensors in the expected format.

First stab at an alternative, BTHome compatible BLE protocol

---

code/nrf-connect/prstlib/boards/arm/bparasite_nrf52833/bparasite_nrf52833.dts
code/nrf-connect/prstlib/boards/arm/bparasite_nrf52833/bparasite_nrf52833_1_1_0.overlay
code/nrf-connect/prstlib/boards/arm/bparasite_nrf52833/bparasite_nrf52833_1_2_0.overlay
code/nrf-connect/prstlib/boards/arm/bparasite_nrf52840/bparasite_nrf52840.dts
code/nrf-connect/prstlib/boards/arm/bparasite_nrf52840/bparasite_nrf52840_1_1_0.overlay
code/nrf-connect/prstlib/boards/arm/bparasite_nrf52840/bparasite_nrf52840_1_2_0.overlay

Potentially fixes the nRF52833 DTS ADC definitions, raised in #76.
@jhbruhn I found a couple of bugs that would explain the ADC errors you're seeing, including the wrong pin config you pointed out. I've ordered myself a couple of nRF52833 for testing. It will take some time to arrive, so unfortunately I can't test these myself, but at least now the config seems to be on par with the nRF52840 variant. Let me know if you manage to take it for spin. Tks!

Fix ADC config for nRF52833

---

code/nrf-connect/samples/ble/src/encoding.c

The counter in the classic b-parasite protocol was missing. This led to the parasite-scanner and esphome implementation to ignore the ble updates. This fixes the problem for me.
Tested with parasite-scanner and esphome

Fix: Counter was missing

---

code/nrf-connect/samples/ble/Kconfig
code/nrf-connect/samples/ble/src/ble.c

We were previously relying on the default values (100ms, 150ms). This PR makes it easier to test and configure parameters for different tradeoffs between range / power consumption (#98).

Make advertisement intervals configurable

---

kitspace.yaml

Following on from https://github.com/rbaron/w-parasite/pull/3 I've added the manifest here. Kitspace can also parse your LCSC BOM (though note that it will infer quantities from references, since there is no quantity column). If you want to work on the BOM using the [bom-builder](https://github.com/kitspace/bom-builder)  ([more info](https://kitspace.org/bom-builder)) let me know and I'll give you access.

Add kitspace.yaml

---

code/nrf-connect/samples/zigbee/src/main.c

The zigbee identify cluster defines an action which can be called e.g. from home assistant to identify the device.
The action is currently not implemented in the device firmware. This PR changes this. 😉 
On calling the identify action the device LED will flash 15 times to identify itself visually. This is especially helpful during provisioning of many devices at the same time.

Added zigbee identify callback

---

code/nrf-connect/samples/ble/src/ble.c

I've been debugging a Shelly [BLE proxy](https://www.home-assistant.io/integrations/shelly/#bluetooth-support) feature, which didn't like b-parasite's advertising. It swallowed it before proxying it to HA.
I compared to the legacy b-parasite advertising (pre-nrf-connect, which does work with Shelly's BLE proxy) and found it to be related to the non-connectable/non-scannable settings. Until this PR, we were mistakenly setting the advertising to scannable, although with no scannable data. The Zephyr code that sets this parameter based on the scannable data is [here](https://github.com/zephyrproject-rtos/zephyr/blob/c0fcd35531611bbe35376c62a9e50744d6904940/subsys/bluetooth/host/adv.c#L860), notably the `|| sd || ` clause.
My bet is that some scanners like ESPHome are okay with this, but …

[ble] Make advertising non-connectable

---

code/nrf-connect/samples/zigbee/CMakeLists.txt
code/nrf-connect/samples/zigbee/Kconfig
code/nrf-connect/samples/zigbee/src/main.c
code/nrf-connect/samples/zigbee/src/restart_handler.c
code/nrf-connect/samples/zigbee/src/restart_handler.h

From the discussion in #126 
This PR implements a timer based mechanism to restart networt steering if the previous steering procedure was not successful. This change will improve the reliability with reconnecting to the network e.g. in cases of power losses or being located at the edge of the network.
Zephyr does only try to reconnect to the network a finite amount of times for end devices. It does so with exponential back of for around 15 minutes. This behaviour is hard coded into Zephyr and not easily changeable.
The official docs suggest reinitializing the steering process by either power cycling the device or via provided method `user_input_indicate()`.
The PR is meant for a basis for discussion and further improvements.
I tried to keep the `main.c` as clean as possible by moving the …

Zigbee schedule steering restart

---

code/nrf-connect/samples/zigbee/Kconfig
code/nrf-connect/samples/zigbee/prj.conf
code/nrf-connect/samples/zigbee/src/factory_reset.c

With this config set, resetting while pressing and holding the SW1 button for 5 seconds will factory reset the device.

[ZigBee sample] Implements factory reset via SW1 button (hardware v2.0.0+)

---

code/nrf-connect/samples/zigbee/Kconfig
code/nrf-connect/samples/zigbee/prj.conf
code/nrf-connect/samples/zigbee/src/debug_counters.c
code/nrf-connect/samples/zigbee/src/factory_reset.c
code/nrf-connect/samples/zigbee/src/main.c
code/nrf-connect/samples/zigbee/src/restart_handler.c

1. `zigbee_configure_sleepy_behavior` must be called before `zigbee_enable` - [source docs](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/zigbee/zigbee_app_utils.html#c.zigbee_configure_sleepy_behavior)
2. `zb_zdo_pim_set_long_poll_interval` must be called after the network is joined - [source docs](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/zboss/3.5.2.0/group__zdo__poll__control.html#ga3aae8929b30e71c872f937771b89c768). On top of that, the argument for the call was incorrect - it expects ms directly. Lowered the default to 10 ms, which is already double the previously working value of 5 ms (SDK default). 
3. Removed the unnecessary `CONFIG_PM`, `CONFIG_PM_DEVICE`. It seems like there's no impact in power consumption. Could it cause some of the …

Fix (minor?) issues with the ZigBee sample

---

README.md
code/nrf-connect/samples/ble/Kconfig
code/nrf-connect/samples/ble/README.md

This change has been planned for a while, and BTHome v2 + Home Assistant is currently the most convenient, hassle-free and maintained way to interface with the BLE sample.

[ble sample] Sets BTHome V2 as the default encoding

---

code/nrf-connect/prstlib/boards/arm/bparasite_nrf52833/bparasite_nrf52833.dts

The nRF52833 has only 512 kB of flash. The .dts file was incorrect, as a product of having it forked from the nRF52840 .dts file, which has 1 MB of flash.
Since we use just a little bit of flash, we luckily never ran into this issue.
The new, correct partitions are closely related to the [nrf52833dk](https://github.com/zephyrproject-rtos/zephyr/blob/ec527228613e2768caaddedaa5cdea04951d3a06/boards/arm/nrf52833dk_nrf52833/nrf52833dk_nrf52833.dts#L215).

Fix nRF52833 flash partitions

---

code/nrf-connect/prstlib/src/adc.c

The ADC sometimes responds with negative voltages read on the ADC input due to noise. This can lead to very high illuminance readings at night (4095 << 4 to be exact due to two's complement :) ). This commit caps ADC readings at 0.

Only read positive voltages in adc.c

---

code/nrf-connect/samples/ble/README.md

Small typo fix in BLE sample README

---

code/nrf-connect/samples/ble/src/encoding.c

Changes in BTHOME_V2 protocol:
- Reduce resolution of humidity and moisture to 1 byte
- Add battery percentage
Refer to issue #187

Report battery percentage in BLE BTHOME_V2 protocol

---

.github/workflows/b-parasite.yml
code/nrf-connect/samples/ble/Kconfig
code/nrf-connect/samples/ble/README.md
code/nrf-connect/samples/ble/prj.conf
code/nrf-connect/samples/ble/src/main.c

As part of unintentional radiator testing, I needed to reduce the loop so that the device is constantly sending data. These changes increase the resolution of the BLE advertizment and loop sleeps allowing me to create a build with a 20ms sleep.
I plan on sending the devices to the lab next week. First time going through this process, if I'm doing a dumb please speak up.

Adjusting sleep durations to be milliseconds. Needed for FCC 15b testing.
